From debian:unstable-slim

RUN apt update && apt upgrade -y && apt install -y locales && rm -rf /var/lib/apt/lists/* && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
RUN apt update && apt upgrade && apt install curl dnsutils net-tools iputils-ping -y 
ENV LANG en_US.utf8
CMD ["/bin/bash"]
